"""Create financial entries table

Revision ID: 863bb7037a6b
Revises: ae03db4ad675
Create Date: 2026-07-31 12:09:00.343966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863bb7037a6b'
down_revision = 'ae03db4ad675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_entries',
    sa.Column('financial_month_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('INCOME', 'EXPENSE', name='entrytype'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['financial_month_id'], ['financial_months.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_entries')
    # ### end Alembic commands ###
