"""Create financial reports table

Revision ID: 94d16dc767ec
Revises: 863bb7037a6b
Create Date: 2026-07-31 12:14:18.718930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d16dc767ec'
down_revision = '863bb7037a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_reports',
    sa.Column('financial_month_id', sa.Integer(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('savings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('savings_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['financial_month_id'], ['financial_months.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_month_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_reports')
    # ### end Alembic commands ###
